// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9ugmVTzUhKYsqFovHZydMg2mYcfQkWo',
    appId: '1:93248186447:web:7835e5b64dd59e9fca4db3',
    messagingSenderId: '93248186447',
    projectId: 'unicv-avisos',
    authDomain: 'unicv-avisos.firebaseapp.com',
    databaseURL: 'https://unicv-avisos-default-rtdb.firebaseio.com',
    storageBucket: 'unicv-avisos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBDWq0tHQ51QQOXhHC5AJAFMJ1cxpBgI',
    appId: '1:93248186447:android:5278af761248ea17ca4db3',
    messagingSenderId: '93248186447',
    projectId: 'unicv-avisos',
    databaseURL: 'https://unicv-avisos-default-rtdb.firebaseio.com',
    storageBucket: 'unicv-avisos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YltkHCXGpU5DyGRF6ElFycUjhkWmav8',
    appId: '1:93248186447:ios:86026bca6b525fdbbfe23a',
    messagingSenderId: '93248186447',
    projectId: 'unicv-avisos',
    databaseURL: 'https://unicv-avisos-default-rtdb.firebaseio.com',
    storageBucket: 'unicv-avisos.appspot.com',
    iosBundleId: 'Unicv-Avisos',  // Use o ID do pacote que foi configurado no Firebase
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7YltkHCXGpU5DyGRF6ElFycUjhkWmav8',
    appId: '1:93248186447:ios:86026bca6b525fdbbfe23a',
    messagingSenderId: '93248186447',
    projectId: 'unicv-avisos',
    databaseURL: 'https://unicv-avisos-default-rtdb.firebaseio.com',
    storageBucket: 'unicv-avisos.appspot.com',
    iosBundleId: 'Unicv-Avisos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIck-3lKrFtJCUWzIV9rcfCmb-eIv9r4s',
    appId: '1:93248186447:web:421f0a2d5a2d7540ca4db3',
    messagingSenderId: '93248186447',
    projectId: 'unicv-avisos',
    authDomain: 'unicv-avisos.firebaseapp.com',
    databaseURL: 'https://unicv-avisos-default-rtdb.firebaseio.com',
    storageBucket: 'unicv-avisos.appspot.com',
  );
}
